import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Visualizar() {
    const [data, setData] = useState([])
    const [message, setMessage] = useState('')
    const router = useRouter()
    const [id] = useState(router.query.id)
    const getLivro = async () => {
        if (id === undefined) {
            setMessage('Erro: Livro não encontrado!')
            return
        }

        await axios.get('http://localhost:8080/livro/' + id)
            .then((response) => { // Acessa o then quando a API retornar status 200
                console.log(response.data.livro)
                setData(response.data.livro)
            }).catch((err) => { 
                if (err.response) {
                    setMessage(err.response.data.mensagem)
                } else {
                    setMessage('Erro: Tente novamente mais tarde!')
                }
            })
    }

    useEffect(() => {
        getLivro()
    }, [id])

    return (
        <>
            <Head>
                <title>Monitora Envios</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href={'/listarLivros'}><button type='button'>Listar</button></Link>{' '}             
                <Link href={`/editarLivro/${data.id}`}><button type='button'>Editar</button></Link>{' '}
                <h3>Detalhes do Livro {data.id}</h3>
                <span><strong>ISBN:</strong> {data.isbn}</span><br />
                <span><strong>Titulo:</strong> {data.titulo}</span><br />
                <span><strong>Autor:</strong> {data.autor}</span><br />
                <span><strong>Editora:</strong> {data.editora}</span><br />
                <span><strong>Tipo Livro:</strong> {data.tipolivro}</span><br />
                <span><strong>Idioma:</strong> {data.idioma}</span><br />
                <span><strong>Estante:</strong> {data.estante}</span><br />
                <span><strong>Ano:</strong> {data.ano}</span><br />
                <span><strong>Preço:</strong> {data.preco}</span><br />
                <span><strong>Edição:</strong> {data.edicao}</span><br />
                <span><strong>Peso:</strong> {data.peso}</span><br />
                <span><strong>Descrição:</strong> {data.descricao}</span><br />
                <span><strong>Categoria:</strong> {data.categoria}</span><br />
                <span><strong>Localização:</strong> {data.localizacao}</span><br />
            </main>
        </>
    )
}
