import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Visualizar() {
    const [dataPedido, setData] = useState([])

    const [message, setMessage] = useState('')
    const router = useRouter()
    const [id] = useState(router.query.id)
    const getPedido = async () => {
        if (id === undefined) {
            setMessage('Erro: pedido não encontrado!')
            return
        }

        await axios.get('http://localhost:8080/pedido/' + id)
            .then((response) => { // Acessa o then quando a API retornar status 200
                console.log(response.data.pedido)
                setData(response.data.pedido)
            }).catch((err) => {
                if (err.response) {
                    setMessage(err.response.data.mensagem)
                } else {
                    setMessage('Erro: Tente novamente mais tarde!')
                }
            })
    }

    useEffect(() => {
        getPedido()
    }, [id])

    return (
        <>
            <Head>
                <title>Monitora Envios</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Link href={"/principal"}><button type='button'>Home</button></Link>{' '}
                <Link href={'/listarPedidos'}><button type='button'>Listar</button></Link>{' '}
                <Link href={`/editarPedido/${dataPedido.id}`}><button type='button'>Editar</button></Link>{' '}
                <br></br>  <br></br>


                <h3>Pedido Nº: {dataPedido.id}</h3>
                <form>
                    <span><strong>Comprador:</strong> {dataPedido.comprador}</span>
                    <span><strong>CPF/CNPJ:</strong> {dataPedido.cpfcnpj}</span>
                </form>
                <h4>Endereço de Entrega: </h4>
                <form>
                    <span><strong>Destinário:</strong> {dataPedido.destinario}</span>
                    <span><strong>Logradouro:</strong> {dataPedido.logradouro}</span>
                    <span><strong>Numero:</strong> {dataPedido.numero}</span>
                    <span><strong>Bairro:</strong> {dataPedido.bairro}</span>
                    <span><strong>Complemento:</strong> {dataPedido.complemento}</span>
                    <span><strong>Cidade:</strong> {dataPedido.cidade}</span>
                    <span><strong>UF:</strong> {dataPedido.uf}</span>
                    <span><strong>CEP:</strong> {dataPedido.cep}</span>
                </form>


                <h4>Detalhes Pedido: </h4>
                <form>
                    <span><strong>Data Pagamento:</strong> {dataPedido.dataPagamento}</span>
                    <span><strong>Forma de Envio:</strong> {dataPedido.formaenvio}</span>
                    <span><strong>Frete:</strong> {dataPedido.frete}</span>
                    <span><strong>Preço:</strong>{'0'} </span>
                    <span><strong>Valor:</strong> {dataPedido.valortotal}</span>
                    <label>{''}</label>
                    <span><strong>Rastreamento:</strong> {dataPedido.codigorastreio}</span>
                    <Link href={"/principal"}><button type='button'>Rastreamento</button></Link>{' '}
                </form>
            </main>
        </>
    )
}