import Head from "next/head";
import { useState } from "react";

export default function Home() {

  const [data, setData] = useState({
    nome: '',
    email: ''
  })
  
  const valueInput = (evento) => setData({...data, [evento.target.nome]: evento.target.value})


  return (
    <>
      <Head>
        <title>Monitora Envios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <h2>Cadastrar Cliente</h2>
        <form>
          <label>Nome:</label>
          <input type='text' name='nome' placeholder='Digite Nome' /><br/><br/>

          <label>E-Mail: </label>
          <input type='email' name='email' placeholder='Digite E-Mail' /><br/><br/>

          <button type='submit'>Salvar</button><br/><br/>



        </form>




      </main>
    </>
  );
}
