import Head from 'next/head'
import { useState } from 'react'
const xlsx = require('xlsx')

export default function Planilha() {
    const [dados, setData] = useState([])
    const [pagina, setPage] = useState('')
    const [ultimaPagina, setLastPage] = useState('')

    const lerDadosArquivo = (e) => {
      const reader = new FileReader()
      reader.readAsBinaryString(e.target.files[0])
      reader.onload = (e) => {
        const data = e.target.result
        const workbook = xlsx.read(data, { type: "binary" })
        const sheetName = workbook.SheetNames[0]
        const sheet = workbook.Sheets[sheetName]
        const parsedData = xlsx.utils.sheet_to_json(sheet)
        setData(parsedData)
      }
    }

    const  importarDados = (e) => {

      }


    return (
        <>
          <Head>
            <title>Celke</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
    
            <h3>Ler dados do arquivo CSV</h3>
    
            <label>Arquivo: </label>
            <input type='file' accept='.xlsx' onChange={lerDadosArquivo} /><br /><br/>

            <button type='button' onClick={() => importarDados(dados)}>Validar</button> <br /><br />
    
            <table>
              <thead>
                <tr>
                  <th>ISBN</th>
                  <th>Autor</th>
                  <th>Titulo</th>
                  <th>Editora</th>
                </tr>
              </thead>
              <tbody>
                {/* Percorrer a lista de registros */}
                {dados.map((row, index) => (
                  <tr key={index}>
                    <td>{row.isbn}</td>
                    <td>{row.autor}</td>
                    <td>{row.titulo}</td>
                    <td>{row.editora}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            
          </main>
        </>
      )
    

}