import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

export default function Principal() {

  const router = useRouter()

  const [mensagem, setMessage] = useState('')
  const valueInput = (e) => setData({ ...data, [e.target.name]: e.target.value });


  return (
    <>
      <Head>
        <title>Monitora Entregas</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h2>Monitoramento de Envios</h2>
        {mensagem ? <p>{mensagem}</p> : ''}
       
          <Link href={'/listarClientes'}> <button type='button'>Clientes</button></Link>{' '}
          <Link href={'/listarLivros'}> <button type='button'>Livros</button></Link>{' '}
     
        <p>Sistema para acompanhar envios de livros</p>

      </main>
    </>
  )

}