import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Editar() {
    const [data, setData] = useState([])
    const [message, setMessage] = useState('')
    const router = useRouter();
    //console.log(router.query.id);
    const [id] = useState(router.query.id)
    const getCliente = async () => {
        if (id === undefined) {
            setMessage('Erro: Cliente não encontrado!')
            return
        }

        await axios.get('http://localhost:8080/cliente/' + id)
            .then((response) => { // Acessa o then quando a API retornar status 200
                console.log(response.data.cliente);
                setData(response.data.cliente);
            }).catch((err) => { 
                if (err.response) {
                    setMessage(err.response.data.mensagem)
                } else {
                    setMessage('Erro: Tente novamente mais tarde!')
                }
            })
    }

    useEffect(() => {
        getCliente()
    }, [id])
    
    const valueInput = (e) => setData({ ...data, [e.target.name]: e.target.value })

    const editarCliente = async (e) => {
        e.preventDefault();

        const headers = {
            'headers': {
                'Content-Type': 'application/json'
            }
        }

        await axios.put('http://localhost:8080/clientes', data, headers)
            .then((response) => {
                setMessage(response.data.mensagem);
            }).catch((err) => {
                if (err.response) {
                    setMessage(err.response.data.mensagem)
                } else {
                    setMessage('Erro: Tente novamente mais tarde ou entre contato com ...!')
                }
            })
    }



    return (
        <>
            <Head>
                <title>Monitora Entregas</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <Link href={'/'}><button type='button'>Listar</button></Link>{' '}
                    <h2>Editar Cliente {data.nome}</h2>
                        {message ? <p>{message}</p> : ''}
                        <form onSubmit={editarCliente}>
                            <label>código: {id} </label><br />
                            <label>Nome: </label>
                            <input type='text' name='nome'  onChange={valueInput} value={data.nome} /><br /><br />
                            <label>E-mail: </label>
                            <input type='email' name='email'  onChange={valueInput} value={data.email} /><br /><br />
                            <button type='submit'>Salvar</button>
                        </form>
            </main>
        </>
    )
}